### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by wushu0725** [niuzhiweimr/redis-spring-boot-starter#2]
public class RedisSingleProcessor extends AbstractRedisProcessor {

    private static Jedis jedis=null;

    private Jedis getSingle() {
        if (jedis == null) {
            JedisConnectionFactory jedisConnectionFactory = getConnectionFactory();
            jedis = (Jedis) jedisConnectionFactory.getConnection().getNativeConnection();
            return jedis;
        }
        return jedis;
    }
我第一次进来取的jedis没问题，第二次直接返回的jedis就没有我配置文件的信息了jedis的dataSoure就是空的？

**Comment by wushu0725** [comment]
单点的时候，我配置文件设置了db是8，前面2次的jredis有值，是8，后面变成0了？

**Comment by niuzhiweimr** [comment]
可以提交个pull requests

**Comment by niuzhiweimr** [comment]
你用的1.0还是2.0？

**Comment by niuzhiweimr** [comment]
jedis.select(jedisConnectionFactory.getDatabase()); 可能能帮助你解决问题，如果解决了麻烦请反馈一下

**Comment by wushu0725** [comment]
不好意思，没看，我发现是RedisSingleProcessor 的close方法
close2次后会把jredis的datasource置为空，注释掉就好了，
不知道是不是bug？
 @Override
    public void close() {
        //把这里注释掉了，不然会有问题
        //jedis.close();
    }

**Comment by wushu0725** [comment]
是我不知哪个依赖哪里引入了clients:jedis:3.1.0，
这个包的close方法会把datasource置为空

**Comment by wushu0725** [comment]
基本上找到原因了，POM引入的springboot版本是2.1.5.RELEASE，
自动依赖引入的jedis是2.9.3，
我引入的版本是2.2.1RELEASE，jedis是3.1

**Comment by niuzhiweimr** [comment]
每次操作需要关闭一次连接单机的
