### ISSUE TITLE
java.lang.ClassCastException: [B 

### ISSUE THREAD

**Issue by blank-1** [niuzhiweimr/redis-spring-boot-starter#3]
![image](https://user-images.githubusercontent.com/30788027/72611459-24cb3a00-3965-11ea-894a-36b862db676a.png)

**Comment by blank-1** [comment]
高并发情况下会出现，version starter 2.1.5

**Comment by blank-1** [comment]
官方bug：https://github.com/niuzhiweimr/redis-spring-boot-starter/issues/3

**Comment by niuzhiweimr** [comment]
多线程同时调度一个jedis对象产生的问题已经修改并更新版本为2.1.0

**Comment by niuzhiweimr** [comment]
代码在master版本未经过测试

**Comment by niuzhiweimr** [comment]
代码在master版本未经过测试
